[opener]
edit = [
    { run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
]
pdf = [
    { run = 'mupdf "$@"', orphan = true, desc = "Open with mupdf", for = "unix" }
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = ["pdf", "reveal"] }
]
