#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           12
bspc config normal_border_color  "#282A2E"
bspc config focused_border_color "#707880"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 move 
bpsc config pointer_action2 resize_corner

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
